version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/${var.project_name}-repo
hooks:
  AfterInstall:
    - location: scripts/restart.sh
      timeout: 300
      runas: ec2-user
